version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: product-catalog-postgres
    environment:
      POSTGRES_DB: product_catalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:emulators
    container_name: pubsub-emulator
    entrypoint: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085
    ports:
      - "8085:8085"



  product-catalog-service:
    build: .
    container_name: product-catalog-service
    depends_on:
      postgres:
        condition: service_healthy

      pubsub-emulator:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/product_catalog
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: pubsub
      SPRING_CLOUD_GCP_PUBSUB_EMULATOR_HOST: pubsub-emulator:8085
      SPRING_RABBITMQ_ENABLED: "false"
      MANAGEMENT_HEALTH_RABBIT_ENABLED: "false"
    ports:
      - "8080:8080"

volumes:
  postgres-data:
